language: go
go:
  - 1.2
before_install:
- go get golang.org/x/tools/cmd/vet
- go get github.com/onsi/ginkgo/...
- go get github.com/onsi/gomega/...
install: true
script: bin/test
branches:
  only:
  - master
